data = [{'account_id': 'DJb8K9rkzdH579zayArnHlo39nQVKXc3rnJek',
  'account_owner': None,
  'amount': 500.0,
  'authorized_date': None,
  'authorized_datetime': None,
  'category': ['Travel', 'Airlines and Aviation Services'],
  'category_id': '22001000',
  'check_number': None,
  'counterparties': [{'confidence_level': 'VERY_HIGH',
                      'entity_id': 'NKDjqyAdQQzpyeD8qpLnX0D6yvLe2KYKYYzQ4',
                      'logo_url': 'https://plaid-merchant-logos.plaid.com/united_airlines_1065.png',
                      'name': 'United Airlines',
                      'phone_number': None,
                      'type': 'merchant',
                      'website': 'united.com'}],
  'date': datetime.date(2023, 12, 11),
  'datetime': None,
  'iso_currency_code': 'USD',
  'location': {'address': None,
               'city': None,
               'country': None,
               'lat': None,
               'lon': None,
               'postal_code': None,
               'region': None,
               'store_number': None},
  'logo_url': 'https://plaid-merchant-logos.plaid.com/united_airlines_1065.png',
  'merchant_entity_id': 'NKDjqyAdQQzpyeD8qpLnX0D6yvLe2KYKYYzQ4',
  'merchant_name': 'United Airlines',
  'name': 'United Airlines',
  'payment_channel': 'in store',
  'payment_meta': {'by_order_of': None,
                   'payee': None,
                   'payer': None,
                   'payment_method': None,
                   'payment_processor': None,
                   'ppd_id': None,
                   'reason': None,
                   'reference_number': None},
  'pending': False,
  'pending_transaction_id': None,
  'personal_finance_category': {'confidence_level': 'VERY_HIGH',
                                'detailed': 'TRAVEL_FLIGHTS',
                                'primary': 'TRAVEL'},
  'personal_finance_category_icon_url': 'https://plaid-category-icons.plaid.com/PFC_TRAVEL.png',
  'transaction_code': None,
  'transaction_id': 'QlxJQaeLG3I5JKRGwmPdHjNQMNj8GJfwVEL6r',
  'transaction_type': 'special',
  'unofficial_currency_code': None,
  'website': 'united.com'},
 {'account_id': 'DJb8K9rkzdH579zayArnHlo39nQVKXc3rnJek',
  'account_owner': None,
  'amount': 500.0,
  'authorized_date': None,
  'authorized_datetime': None,
  'category': ['Food and Drink', 'Restaurants'],
  'category_id': '13005000',
  'check_number': None,
  'counterparties': [],
  'date': datetime.date(2023, 12, 6),
  'datetime': None,
  'iso_currency_code': 'USD',
  'location': {'address': None,
               'city': None,
               'country': None,
               'lat': None,
               'lon': None,
               'postal_code': None,
               'region': None,
               'store_number': None},
  'logo_url': None,
  'merchant_entity_id': None,
  'merchant_name': None,
  'name': 'Tectra Inc',
  'payment_channel': 'in store',
  'payment_meta': {'by_order_of': None,
                   'payee': None,
                   'payer': None,
                   'payment_method': None,
                   'payment_processor': None,
                   'ppd_id': None,
                   'reason': None,
                   'reference_number': None},
  'pending': False,
  'pending_transaction_id': None,
  'personal_finance_category': {'confidence_level': 'LOW',
                                'detailed': 'ENTERTAINMENT_SPORTING_EVENTS_AMUSEMENT_PARKS_AND_MUSEUMS',
                                'primary': 'ENTERTAINMENT'},
  'personal_finance_category_icon_url': 'https://plaid-category-icons.plaid.com/PFC_ENTERTAINMENT.png',
  'transaction_code': None,
  'transaction_id': 'ZaQqwGxnymfKX86JjGx1Ig9y79gvMWTeBVwm8',
  'transaction_type': 'place',
  'unofficial_currency_code': None,
  'website': None},
 {'account_id': 'DJb8K9rkzdH579zayArnHlo39nQVKXc3rnJek',
  'account_owner': None,
  'amount': 500.0,
  'authorized_date': None,
  'authorized_datetime': None,
  'category': ['Shops', 'Sporting Goods'],
  'category_id': '19046000',
  'check_number': None,
  'counterparties': [],
  'date': datetime.date(2023, 12, 5),
  'datetime': None,
  'iso_currency_code': 'USD',
  'location': {'address': None,
               'city': None,
               'country': None,
               'lat': None,
               'lon': None,
               'postal_code': None,
               'region': None,
               'store_number': None},
  'logo_url': None,
  'merchant_entity_id': None,
  'merchant_name': None,
  'name': 'Madison Bicycle Shop',
  'payment_channel': 'in store',
  'payment_meta': {'by_order_of': None,
                   'payee': None,
                   'payer': None,
                   'payment_method': None,
                   'payment_processor': None,
                   'ppd_id': None,
                   'reason': None,
                   'reference_number': None},
  'pending': False,
  'pending_transaction_id': None,
  'personal_finance_category': {'confidence_level': 'LOW',
                                'detailed': 'GENERAL_MERCHANDISE_SPORTING_GOODS',
                                'primary': 'GENERAL_MERCHANDISE'},
  'personal_finance_category_icon_url': 'https://plaid-category-icons.plaid.com/PFC_GENERAL_MERCHANDISE.png',
  'transaction_code': None,
  'transaction_id': 'MJr79B1QNKH5ZEQjeGg6Ha4el4ad3mcLrVAp9',
  'transaction_type': 'place',
  'unofficial_currency_code': None,
  'website': None},
 {'account_id': 'DJb8K9rkzdH579zayArnHlo39nQVKXc3rnJek',
  'account_owner': None,
  'amount': 500.0,
  'authorized_date': None,
  'authorized_datetime': None,
  'category': ['Food and Drink', 'Restaurants', 'Fast Food'],
  'category_id': '13005032',
  'check_number': None,
  'counterparties': [{'confidence_level': 'VERY_HIGH',
                      'entity_id': '3LmdknrdwVy9vm0dqj417rLKeJXW7veV7eb2e',
                      'logo_url': 'https://plaid-merchant-logos.plaid.com/kfc_546.png',
                      'name': 'KFC',
                      'phone_number': None,
                      'type': 'merchant',
                      'website': 'kfc.com'}],
  'date': datetime.date(2023, 12, 5),
  'datetime': None,
  'iso_currency_code': 'USD',
  'location': {'address': None,
               'city': None,
               'country': None,
               'lat': None,
               'lon': None,
               'postal_code': None,
               'region': None,
               'store_number': None},
  'logo_url': 'https://plaid-merchant-logos.plaid.com/kfc_546.png',
  'merchant_entity_id': '3LmdknrdwVy9vm0dqj417rLKeJXW7veV7eb2e',
  'merchant_name': 'KFC',
  'name': 'KFC',
  'payment_channel': 'in store',
  'payment_meta': {'by_order_of': None,
                   'payee': None,
                   'payer': None,
                   'payment_method': None,
                   'payment_processor': None,
                   'ppd_id': None,
                   'reason': None,
                   'reference_number': None},
  'pending': False,
  'pending_transaction_id': None,
  'personal_finance_category': {'confidence_level': 'VERY_HIGH',
                                'detailed': 'FOOD_AND_DRINK_FAST_FOOD',
                                'primary': 'FOOD_AND_DRINK'},
  'personal_finance_category_icon_url': 'https://plaid-category-icons.plaid.com/PFC_FOOD_AND_DRINK.png',
  'transaction_code': None,
  'transaction_id': '1QNlrDegM9CqvGEPbWjdIr69J6rk4aCp1lyXp',
  'transaction_type': 'place',
  'unofficial_currency_code': None,
  'website': 'kfc.com'},
 {'account_id': 'DJb8K9rkzdH579zayArnHlo39nQVKXc3rnJek',
  'account_owner': None,
  'amount': 2078.5,
  'authorized_date': None,
  'authorized_datetime': None,
  'category': ['Payment'],
  'category_id': '16000000',
  'check_number': None,
  'counterparties': [],
  'date': datetime.date(2023, 12, 5),
  'datetime': None,
  'iso_currency_code': 'USD',
  'location': {'address': None,
               'city': None,
               'country': None,
               'lat': None,
               'lon': None,
               'postal_code': None,
               'region': None,
               'store_number': None},
  'logo_url': None,
  'merchant_entity_id': None,
  'merchant_name': None,
  'name': 'AUTOMATIC PAYMENT - THANK',
  'payment_channel': 'online',
  'payment_meta': {'by_order_of': None,
                   'payee': None,
                   'payer': None,
                   'payment_method': None,
                   'payment_processor': None,
                   'ppd_id': None,
                   'reason': None,
                   'reference_number': None},
  'pending': False,
  'pending_transaction_id': None,
  'personal_finance_category': {'confidence_level': 'LOW',
                                'detailed': 'GENERAL_MERCHANDISE_OTHER_GENERAL_MERCHANDISE',
                                'primary': 'GENERAL_MERCHANDISE'},
  'personal_finance_category_icon_url': 'https://plaid-category-icons.plaid.com/PFC_GENERAL_MERCHANDISE.png',
  'transaction_code': None,
  'transaction_id': 'LJKVGzReNqH5wJzRrjpDHdeWQedn7Eik5G4Ke',
  'transaction_type': 'special',
  'unofficial_currency_code': None,
  'website': None},
 {'account_id': 'VBPWo7XEyNH561VNEZovHMq3gxjL7Wi9vREkX',
  'account_owner': None,
  'amount': 5850.0,
  'authorized_date': None,
  'authorized_datetime': None,
  'category': ['Transfer', 'Debit'],
  'category_id': '21006000',
  'check_number': None,
  'counterparties': [],
  'date': datetime.date(2023, 12, 25),
  'datetime': None,
  'iso_currency_code': 'USD',
  'location': {'address': None,
               'city': None,
               'country': None,
               'lat': None,
               'lon': None,
               'postal_code': None,
               'region': None,
               'store_number': None},
  'logo_url': None,
  'merchant_entity_id': None,
  'merchant_name': None,
  'name': 'ACH Electronic CreditGUSTO PAY 123456',
  'payment_channel': 'online',
  'payment_meta': {'by_order_of': None,
                   'payee': None,
                   'payer': None,
                   'payment_method': 'ACH',
                   'payment_processor': None,
                   'ppd_id': None,
                   'reason': None,
                   'reference_number': None},
  'pending': False,
  'pending_transaction_id': None,
  'personal_finance_category': {'confidence_level': 'LOW',
                                'detailed': 'GENERAL_SERVICES_ACCOUNTING_AND_FINANCIAL_PLANNING',
                                'primary': 'GENERAL_SERVICES'},
  'personal_finance_category_icon_url': 'https://plaid-category-icons.plaid.com/PFC_GENERAL_SERVICES.png',
  'transaction_code': None,
  'transaction_id': 'pvK5bdJQRWHz47X9wLBeI5qoMq5RGXhpd36jE',
  'transaction_type': 'special',
  'unofficial_currency_code': None,
  'website': None},
 {'account_id': 'VBPWo7XEyNH561VNEZovHMq3gxjL7Wi9vREkX',
  'account_owner': None,
  'amount': 5850.0,
  'authorized_date': None,
  'authorized_datetime': None,
  'category': ['Transfer', 'Debit'],
  'category_id': '21006000',
  'check_number': None,
  'counterparties': [],
  'date': datetime.date(2023, 11, 25),
  'datetime': None,
  'iso_currency_code': 'USD',
  'location': {'address': None,
               'city': None,
               'country': None,
               'lat': None,
               'lon': None,
               'postal_code': None,
               'region': None,
               'store_number': None},
  'logo_url': None,
  'merchant_entity_id': None,
  'merchant_name': None,
  'name': 'ACH Electronic CreditGUSTO PAY 123456',
  'payment_channel': 'online',
  'payment_meta': {'by_order_of': None,
                   'payee': None,
                   'payer': None,
                   'payment_method': 'ACH',
                   'payment_processor': None,
                   'ppd_id': None,
                   'reason': None,
                   'reference_number': None},
  'pending': False,
  'pending_transaction_id': None,
  'personal_finance_category': {'confidence_level': 'LOW',
                                'detailed': 'GENERAL_SERVICES_ACCOUNTING_AND_FINANCIAL_PLANNING',
                                'primary': 'GENERAL_SERVICES'},
  'personal_finance_category_icon_url': 'https://plaid-category-icons.plaid.com/PFC_GENERAL_SERVICES.png',
  'transaction_code': None,
  'transaction_id': 'ovq5ZkRemwHr4zgJQZAoCNPGePNm39iom8B5K',
  'transaction_type': 'special',
  'unofficial_currency_code': None,
  'website': None},
 {'account_id': 'Rqd8J4epyxu5evjGgZPLH7PVAXndgbCaLJAjn',
  'account_owner': None,
  'amount': -500.0,
  'authorized_date': datetime.date(2023, 11, 24),
  'authorized_datetime': None,
  'category': ['Travel', 'Airlines and Aviation Services'],
  'category_id': '22001000',
  'check_number': None,
  'counterparties': [{'confidence_level': 'VERY_HIGH',
                      'entity_id': 'NKDjqyAdQQzpyeD8qpLnX0D6yvLe2KYKYYzQ4',
                      'logo_url': 'https://plaid-merchant-logos.plaid.com/united_airlines_1065.png',
                      'name': 'United Airlines',
                      'phone_number': None,
                      'type': 'merchant',
                      'website': 'united.com'}],
  'date': datetime.date(2023, 11, 24),
  'datetime': None,
  'iso_currency_code': 'USD',
  'location': {'address': None,
               'city': None,
               'country': None,
               'lat': None,
               'lon': None,
               'postal_code': None,
               'region': None,
               'store_number': None},
  'logo_url': 'https://plaid-merchant-logos.plaid.com/united_airlines_1065.png',
  'merchant_entity_id': 'NKDjqyAdQQzpyeD8qpLnX0D6yvLe2KYKYYzQ4',
  'merchant_name': 'United Airlines',
  'name': 'United Airlines',
  'payment_channel': 'in store',
  'payment_meta': {'by_order_of': None,
                   'payee': None,
                   'payer': None,
                   'payment_method': None,
                   'payment_processor': None,
                   'ppd_id': None,
                   'reason': None,
                   'reference_number': None},
  'pending': False,
  'pending_transaction_id': None,
  'personal_finance_category': {'confidence_level': 'VERY_HIGH',
                                'detailed': 'TRAVEL_FLIGHTS',
                                'primary': 'TRAVEL'},
  'personal_finance_category_icon_url': 'https://plaid-category-icons.plaid.com/PFC_TRAVEL.png',
  'transaction_code': None,
  'transaction_id': 'pvK5bdJQRWHz47X9wLBeI5q84V4y75sJ3qBG9',
  'transaction_type': 'special',
  'unofficial_currency_code': None,
  'website': 'united.com'},
 {'account_id': 'Rqd8J4epyxu5evjGgZPLH7PVAXndgbCaLJAjn',
  'account_owner': None,
  'amount': 12.0,
  'authorized_date': datetime.date(2023, 11, 23),
  'authorized_datetime': None,
  'category': ['Food and Drink', 'Restaurants', 'Fast Food'],
  'category_id': '13005032',
  'check_number': None,
  'counterparties': [{'confidence_level': 'VERY_HIGH',
                      'entity_id': 'vzWXDWBjB06j5BJoD3Jo84OJZg7JJzmqOZA22',
                      'logo_url': 'https://plaid-merchant-logos.plaid.com/mcdonalds_619.png',
                      'name': "McDonald's",
                      'phone_number': None,
                      'type': 'merchant',
                      'website': 'mcdonalds.com'}],
  'date': datetime.date(2023, 11, 23),
  'datetime': None,
  'iso_currency_code': 'USD',
  'location': {'address': None,
               'city': None,
               'country': None,
               'lat': None,
               'lon': None,
               'postal_code': None,
               'region': None,
               'store_number': '3322'},
  'logo_url': 'https://plaid-merchant-logos.plaid.com/mcdonalds_619.png',
  'merchant_entity_id': 'vzWXDWBjB06j5BJoD3Jo84OJZg7JJzmqOZA22',
  'merchant_name': "McDonald's",
  'name': "McDonald's",
  'payment_channel': 'in store',
  'payment_meta': {'by_order_of': None,
                   'payee': None,
                   'payer': None,
                   'payment_method': None,
                   'payment_processor': None,
                   'ppd_id': None,
                   'reason': None,
                   'reference_number': None},
  'pending': False,
  'pending_transaction_id': None,
  'personal_finance_category': {'confidence_level': 'VERY_HIGH',
                                'detailed': 'FOOD_AND_DRINK_FAST_FOOD',
                                'primary': 'FOOD_AND_DRINK'},
  'personal_finance_category_icon_url': 'https://plaid-category-icons.plaid.com/PFC_FOOD_AND_DRINK.png',
  'transaction_code': None,
  'transaction_id': 'ovq5ZkRemwHr4zgJQZAoCNPql6ljDNFp8PgDX',
  'transaction_type': 'place',
  'unofficial_currency_code': None,
  'website': 'mcdonalds.com'},
 {'account_id': 'Rqd8J4epyxu5evjGgZPLH7PVAXndgbCaLJAjn',
  'account_owner': None,
  'amount': 4.33,
  'authorized_date': datetime.date(2023, 11, 23),
  'authorized_datetime': None,
  'category': ['Food and Drink', 'Restaurants', 'Coffee Shop'],
  'category_id': '13005043',
  'check_number': None,
  'counterparties': [{'confidence_level': 'VERY_HIGH',
                      'entity_id': 'NZAJQ5wYdo1W1p39X5q5gpb15OMe39pj4pJBb',
                      'logo_url': 'https://plaid-merchant-logos.plaid.com/starbucks_956.png',
                      'name': 'Starbucks',
                      'phone_number': None,
                      'type': 'merchant',
                      'website': 'starbucks.com'}],
  'date': datetime.date(2023, 11, 23),
  'datetime': None,
  'iso_currency_code': 'USD',
  'location': {'address': None,
               'city': None,
               'country': None,
               'lat': None,
               'lon': None,
               'postal_code': None,
               'region': None,
               'store_number': None},
  'logo_url': 'https://plaid-merchant-logos.plaid.com/starbucks_956.png',
  'merchant_entity_id': 'NZAJQ5wYdo1W1p39X5q5gpb15OMe39pj4pJBb',
  'merchant_name': 'Starbucks',
  'name': 'Starbucks',
  'payment_channel': 'in store',
  'payment_meta': {'by_order_of': None,
                   'payee': None,
                   'payer': None,
                   'payment_method': None,
                   'payment_processor': None,
                   'ppd_id': None,
                   'reason': None,
                   'reference_number': None},
  'pending': False,
  'pending_transaction_id': None,
  'personal_finance_category': {'confidence_level': 'VERY_HIGH',
                                'detailed': 'FOOD_AND_DRINK_COFFEE',
                                'primary': 'FOOD_AND_DRINK'},
  'personal_finance_category_icon_url': 'https://plaid-category-icons.plaid.com/PFC_FOOD_AND_DRINK.png',
  'transaction_code': None,
  'transaction_id': 'gonbwLrxamted371X8Dahm3M1n1GrmsLqGzBg',
  'transaction_type': 'place',
  'unofficial_currency_code': None,
  'website': 'starbucks.com'},
 {'account_id': 'Rqd8J4epyxu5evjGgZPLH7PVAXndgbCaLJAjn',
  'account_owner': None,
  'amount': 89.4,
  'authorized_date': datetime.date(2023, 11, 21),
  'authorized_datetime': None,
  'category': ['Food and Drink', 'Restaurants'],
  'category_id': '13005000',
  'check_number': None,
  'counterparties': [{'confidence_level': 'LOW',
                      'entity_id': None,
                      'logo_url': None,
                      'name': 'FUN',
                      'phone_number': None,
                      'type': 'merchant',
                      'website': None}],
  'date': datetime.date(2023, 11, 22),
  'datetime': None,
  'iso_currency_code': 'USD',
  'location': {'address': None,
               'city': None,
               'country': None,
               'lat': None,
               'lon': None,
               'postal_code': None,
               'region': None,
               'store_number': None},
  'logo_url': None,
  'merchant_entity_id': None,
  'merchant_name': 'FUN',
  'name': 'SparkFun',
  'payment_channel': 'in store',
  'payment_meta': {'by_order_of': None,
                   'payee': None,
                   'payer': None,
                   'payment_method': None,
                   'payment_processor': None,
                   'ppd_id': None,
                   'reason': None,
                   'reference_number': None},
  'pending': False,
  'pending_transaction_id': None,
  'personal_finance_category': {'confidence_level': 'LOW',
                                'detailed': 'ENTERTAINMENT_SPORTING_EVENTS_AMUSEMENT_PARKS_AND_MUSEUMS',
                                'primary': 'ENTERTAINMENT'},
  'personal_finance_category_icon_url': 'https://plaid-category-icons.plaid.com/PFC_ENTERTAINMENT.png',
  'transaction_code': None,
  'transaction_id': '8gMp48xbj9CdMp1QxPyRsv8gEnEb1vfZjRM6W',
  'transaction_type': 'place',
  'unofficial_currency_code': None,
  'website': None},
 {'account_id': 'Rqd8J4epyxu5evjGgZPLH7PVAXndgbCaLJAjn',
  'account_owner': None,
  'amount': 6.33,
  'authorized_date': datetime.date(2023, 11, 8),
  'authorized_datetime': None,
  'category': ['Travel', 'Taxi'],
  'category_id': '22016000',
  'check_number': None,
  'counterparties': [{'confidence_level': 'VERY_HIGH',
                      'entity_id': 'eyg8o776k0QmNgVpAmaQj4WgzW9Qzo6O51gdd',
                      'logo_url': 'https://plaid-merchant-logos.plaid.com/uber_1060.png',
                      'name': 'Uber',
                      'phone_number': None,
                      'type': 'merchant',
                      'website': 'uber.com'}],
  'date': datetime.date(2023, 11, 9),
  'datetime': None,
  'iso_currency_code': 'USD',
  'location': {'address': None,
               'city': None,
               'country': None,
               'lat': None,
               'lon': None,
               'postal_code': None,
               'region': None,
               'store_number': None},
  'logo_url': 'https://plaid-merchant-logos.plaid.com/uber_1060.png',
  'merchant_entity_id': 'eyg8o776k0QmNgVpAmaQj4WgzW9Qzo6O51gdd',
  'merchant_name': 'Uber',
  'name': 'Uber 072515 SF**POOL**',
  'payment_channel': 'online',
  'payment_meta': {'by_order_of': None,
                   'payee': None,
                   'payer': None,
                   'payment_method': None,
                   'payment_processor': None,
                   'ppd_id': None,
                   'reason': None,
                   'reference_number': None},
  'pending': False,
  'pending_transaction_id': None,
  'personal_finance_category': {'confidence_level': 'VERY_HIGH',
                                'detailed': 'TRANSPORTATION_TAXIS_AND_RIDE_SHARES',
                                'primary': 'TRANSPORTATION'},
  'personal_finance_category_icon_url': 'https://plaid-category-icons.plaid.com/PFC_TRANSPORTATION.png',
  'transaction_code': None,
  'transaction_id': 'EJm9RgzdBkH5Ll1ZW4wKHql4LWLaGqfgJMG7g',
  'transaction_type': 'special',
  'unofficial_currency_code': None,
  'website': 'uber.com'},
 {'account_id': 'Rqd8J4epyxu5evjGgZPLH7PVAXndgbCaLJAjn',
  'account_owner': None,
  'amount': 5.4,
  'authorized_date': datetime.date(2023, 10, 26),
  'authorized_datetime': None,
  'category': ['Travel', 'Taxi'],
  'category_id': '22016000',
  'check_number': None,
  'counterparties': [{'confidence_level': 'VERY_HIGH',
                      'entity_id': 'eyg8o776k0QmNgVpAmaQj4WgzW9Qzo6O51gdd',
                      'logo_url': 'https://plaid-merchant-logos.plaid.com/uber_1060.png',
                      'name': 'Uber',
                      'phone_number': None,
                      'type': 'merchant',
                      'website': 'uber.com'}],
  'date': datetime.date(2023, 10, 27),
  'datetime': None,
  'iso_currency_code': 'USD',
  'location': {'address': None,
               'city': None,
               'country': None,
               'lat': None,
               'lon': None,
               'postal_code': None,
               'region': None,
               'store_number': None},
  'logo_url': 'https://plaid-merchant-logos.plaid.com/uber_1060.png',
  'merchant_entity_id': 'eyg8o776k0QmNgVpAmaQj4WgzW9Qzo6O51gdd',
  'merchant_name': 'Uber',
  'name': 'Uber 063015 SF**POOL**',
  'payment_channel': 'online',
  'payment_meta': {'by_order_of': None,
                   'payee': None,
                   'payer': None,
                   'payment_method': None,
                   'payment_processor': None,
                   'ppd_id': None,
                   'reason': None,
                   'reference_number': None},
  'pending': False,
  'pending_transaction_id': None,
  'personal_finance_category': {'confidence_level': 'VERY_HIGH',
                                'detailed': 'TRANSPORTATION_TAXIS_AND_RIDE_SHARES',
                                'primary': 'TRANSPORTATION'},
  'personal_finance_category_icon_url': 'https://plaid-category-icons.plaid.com/PFC_TRANSPORTATION.png',
  'transaction_code': None,
  'transaction_id': 'W3jRweoWyPI5bgVejMKGH1PJyGyKo1uPK5n8w',
  'transaction_type': 'special',
  'unofficial_currency_code': None,
  'website': 'uber.com'},
 {'account_id': 'Rqd8J4epyxu5evjGgZPLH7PVAXndgbCaLJAjn',
  'account_owner': None,
  'amount': -500.0,
  'authorized_date': datetime.date(2023, 10, 25),
  'authorized_datetime': None,
  'category': ['Travel', 'Airlines and Aviation Services'],
  'category_id': '22001000',
  'check_number': None,
  'counterparties': [{'confidence_level': 'VERY_HIGH',
                      'entity_id': 'NKDjqyAdQQzpyeD8qpLnX0D6yvLe2KYKYYzQ4',
                      'logo_url': 'https://plaid-merchant-logos.plaid.com/united_airlines_1065.png',
                      'name': 'United Airlines',
                      'phone_number': None,
                      'type': 'merchant',
                      'website': 'united.com'}],
  'date': datetime.date(2023, 10, 25),
  'datetime': None,
  'iso_currency_code': 'USD',
  'location': {'address': None,
               'city': None,
               'country': None,
               'lat': None,
               'lon': None,
               'postal_code': None,
               'region': None,
               'store_number': None},
  'logo_url': 'https://plaid-merchant-logos.plaid.com/united_airlines_1065.png',
  'merchant_entity_id': 'NKDjqyAdQQzpyeD8qpLnX0D6yvLe2KYKYYzQ4',
  'merchant_name': 'United Airlines',
  'name': 'United Airlines',
  'payment_channel': 'in store',
  'payment_meta': {'by_order_of': None,
                   'payee': None,
                   'payer': None,
                   'payment_method': None,
                   'payment_processor': None,
                   'ppd_id': None,
                   'reason': None,
                   'reference_number': None},
  'pending': False,
  'pending_transaction_id': None,
  'personal_finance_category': {'confidence_level': 'VERY_HIGH',
                                'detailed': 'TRAVEL_FLIGHTS',
                                'primary': 'TRAVEL'},
  'personal_finance_category_icon_url': 'https://plaid-category-icons.plaid.com/PFC_TRAVEL.png',
  'transaction_code': None,
  'transaction_id': 'AJAn5vlzkBHZmVkgoPQ1IyXxLWLQjyt4EkZDo',
  'transaction_type': 'special',
  'unofficial_currency_code': None,
  'website': 'united.com'},
 {'account_id': 'Rqd8J4epyxu5evjGgZPLH7PVAXndgbCaLJAjn',
  'account_owner': None,
  'amount': 12.0,
  'authorized_date': datetime.date(2023, 10, 24),
  'authorized_datetime': None,
  'category': ['Food and Drink', 'Restaurants', 'Fast Food'],
  'category_id': '13005032',
  'check_number': None,
  'counterparties': [{'confidence_level': 'VERY_HIGH',
                      'entity_id': 'vzWXDWBjB06j5BJoD3Jo84OJZg7JJzmqOZA22',
                      'logo_url': 'https://plaid-merchant-logos.plaid.com/mcdonalds_619.png',
                      'name': "McDonald's",
                      'phone_number': None,
                      'type': 'merchant',
                      'website': 'mcdonalds.com'}],
  'date': datetime.date(2023, 10, 24),
  'datetime': None,
  'iso_currency_code': 'USD',
  'location': {'address': None,
               'city': None,
               'country': None,
               'lat': None,
               'lon': None,
               'postal_code': None,
               'region': None,
               'store_number': '3322'},
  'logo_url': 'https://plaid-merchant-logos.plaid.com/mcdonalds_619.png',
  'merchant_entity_id': 'vzWXDWBjB06j5BJoD3Jo84OJZg7JJzmqOZA22',
  'merchant_name': "McDonald's",
  'name': "McDonald's",
  'payment_channel': 'in store',
  'payment_meta': {'by_order_of': None,
                   'payee': None,
                   'payer': None,
                   'payment_method': None,
                   'payment_processor': None,
                   'ppd_id': None,
                   'reason': None,
                   'reference_number': None},
  'pending': False,
  'pending_transaction_id': None,
  'personal_finance_category': {'confidence_level': 'VERY_HIGH',
                                'detailed': 'FOOD_AND_DRINK_FAST_FOOD',
                                'primary': 'FOOD_AND_DRINK'},
  'personal_finance_category_icon_url': 'https://plaid-category-icons.plaid.com/PFC_FOOD_AND_DRINK.png',
  'transaction_code': None,
  'transaction_id': 'GJ9QbEG4xNH58m4kDWRNHrGnQAQ3ertGyLmv8',
  'transaction_type': 'place',
  'unofficial_currency_code': None,
  'website': 'mcdonalds.com'},
 {'account_id': 'Rqd8J4epyxu5evjGgZPLH7PVAXndgbCaLJAjn',
  'account_owner': None,
  'amount': 4.33,
  'authorized_date': datetime.date(2023, 10, 24),
  'authorized_datetime': None,
  'category': ['Food and Drink', 'Restaurants', 'Coffee Shop'],
  'category_id': '13005043',
  'check_number': None,
  'counterparties': [{'confidence_level': 'VERY_HIGH',
                      'entity_id': 'NZAJQ5wYdo1W1p39X5q5gpb15OMe39pj4pJBb',
                      'logo_url': 'https://plaid-merchant-logos.plaid.com/starbucks_956.png',
                      'name': 'Starbucks',
                      'phone_number': None,
                      'type': 'merchant',
                      'website': 'starbucks.com'}],
  'date': datetime.date(2023, 10, 24),
  'datetime': None,
  'iso_currency_code': 'USD',
  'location': {'address': None,
               'city': None,
               'country': None,
               'lat': None,
               'lon': None,
               'postal_code': None,
               'region': None,
               'store_number': None},
  'logo_url': 'https://plaid-merchant-logos.plaid.com/starbucks_956.png',
  'merchant_entity_id': 'NZAJQ5wYdo1W1p39X5q5gpb15OMe39pj4pJBb',
  'merchant_name': 'Starbucks',
  'name': 'Starbucks',
  'payment_channel': 'in store',
  'payment_meta': {'by_order_of': None,
                   'payee': None,
                   'payer': None,
                   'payment_method': None,
                   'payment_processor': None,
                   'ppd_id': None,
                   'reason': None,
                   'reference_number': None},
  'pending': False,
  'pending_transaction_id': None,
  'personal_finance_category': {'confidence_level': 'VERY_HIGH',
                                'detailed': 'FOOD_AND_DRINK_COFFEE',
                                'primary': 'FOOD_AND_DRINK'},
  'personal_finance_category_icon_url': 'https://plaid-category-icons.plaid.com/PFC_FOOD_AND_DRINK.png',
  'transaction_code': None,
  'transaction_id': 'nvl5m3X7Q8HKQoaBnJrxIpXzZ6ZPRpF3wXrRZ',
  'transaction_type': 'place',
  'unofficial_currency_code': None,
  'website': 'starbucks.com'},
 {'account_id': 'Rqd8J4epyxu5evjGgZPLH7PVAXndgbCaLJAjn',
  'account_owner': None,
  'amount': 89.4,
  'authorized_date': datetime.date(2023, 10, 22),
  'authorized_datetime': None,
  'category': ['Food and Drink', 'Restaurants'],
  'category_id': '13005000',
  'check_number': None,
  'counterparties': [{'confidence_level': 'LOW',
                      'entity_id': None,
                      'logo_url': None,
                      'name': 'FUN',
                      'phone_number': None,
                      'type': 'merchant',
                      'website': None}],
  'date': datetime.date(2023, 10, 23),
  'datetime': None,
  'iso_currency_code': 'USD',
  'location': {'address': None,
               'city': None,
               'country': None,
               'lat': None,
               'lon': None,
               'postal_code': None,
               'region': None,
               'store_number': None},
  'logo_url': None,
  'merchant_entity_id': None,
  'merchant_name': 'FUN',
  'name': 'SparkFun',
  'payment_channel': 'in store',
  'payment_meta': {'by_order_of': None,
                   'payee': None,
                   'payer': None,
                   'payment_method': None,
                   'payment_processor': None,
                   'ppd_id': None,
                   'reason': None,
                   'reference_number': None},
  'pending': False,
  'pending_transaction_id': None,
  'personal_finance_category': {'confidence_level': 'LOW',
                                'detailed': 'GENERAL_MERCHANDISE_OTHER_GENERAL_MERCHANDISE',
                                'primary': 'GENERAL_MERCHANDISE'},
  'personal_finance_category_icon_url': 'https://plaid-category-icons.plaid.com/PFC_GENERAL_MERCHANDISE.png',
  'transaction_code': None,
  'transaction_id': 'bZkxe9aKzmI4rRNMw87atzomP5PljzfoQJajB',
  'transaction_type': 'place',
  'unofficial_currency_code': None,
  'website': None},
 {'account_id': 'Rqd8J4epyxu5evjGgZPLH7PVAXndgbCaLJAjn',
  'account_owner': None,
  'amount': 6.33,
  'authorized_date': datetime.date(2023, 10, 9),
  'authorized_datetime': None,
  'category': ['Travel', 'Taxi'],
  'category_id': '22016000',
  'check_number': None,
  'counterparties': [{'confidence_level': 'VERY_HIGH',
                      'entity_id': 'eyg8o776k0QmNgVpAmaQj4WgzW9Qzo6O51gdd',
                      'logo_url': 'https://plaid-merchant-logos.plaid.com/uber_1060.png',
                      'name': 'Uber',
                      'phone_number': None,
                      'type': 'merchant',
                      'website': 'uber.com'}],
  'date': datetime.date(2023, 10, 10),
  'datetime': None,
  'iso_currency_code': 'USD',
  'location': {'address': None,
               'city': None,
               'country': None,
               'lat': None,
               'lon': None,
               'postal_code': None,
               'region': None,
               'store_number': None},
  'logo_url': 'https://plaid-merchant-logos.plaid.com/uber_1060.png',
  'merchant_entity_id': 'eyg8o776k0QmNgVpAmaQj4WgzW9Qzo6O51gdd',
  'merchant_name': 'Uber',
  'name': 'Uber 072515 SF**POOL**',
  'payment_channel': 'online',
  'payment_meta': {'by_order_of': None,
                   'payee': None,
                   'payer': None,
                   'payment_method': None,
                   'payment_processor': None,
                   'ppd_id': None,
                   'reason': None,
                   'reference_number': None},
  'pending': False,
  'pending_transaction_id': None,
  'personal_finance_category': {'confidence_level': 'VERY_HIGH',
                                'detailed': 'TRANSPORTATION_TAXIS_AND_RIDE_SHARES',
                                'primary': 'TRANSPORTATION'},
  'personal_finance_category_icon_url': 'https://plaid-category-icons.plaid.com/PFC_TRANSPORTATION.png',
  'transaction_code': None,
  'transaction_id': 'mvR5WBejX8Hq4GJ5PjKBIWlw3o3GAWi4zlxNk',
  'transaction_type': 'special',
  'unofficial_currency_code': None,
  'website': 'uber.com'},
 {'account_id': 'Rqd8J4epyxu5evjGgZPLH7PVAXndgbCaLJAjn',
  'account_owner': None,
  'amount': 5.4,
  'authorized_date': datetime.date(2023, 9, 26),
  'authorized_datetime': None,
  'category': ['Travel', 'Taxi'],
  'category_id': '22016000',
  'check_number': None,
  'counterparties': [{'confidence_level': 'VERY_HIGH',
                      'entity_id': 'eyg8o776k0QmNgVpAmaQj4WgzW9Qzo6O51gdd',
                      'logo_url': 'https://plaid-merchant-logos.plaid.com/uber_1060.png',
                      'name': 'Uber',
                      'phone_number': None,
                      'type': 'merchant',
                      'website': 'uber.com'}],
  'date': datetime.date(2023, 9, 27),
  'datetime': None,
  'iso_currency_code': 'USD',
  'location': {'address': None,
               'city': None,
               'country': None,
               'lat': None,
               'lon': None,
               'postal_code': None,
               'region': None,
               'store_number': None},
  'logo_url': 'https://plaid-merchant-logos.plaid.com/uber_1060.png',
  'merchant_entity_id': 'eyg8o776k0QmNgVpAmaQj4WgzW9Qzo6O51gdd',
  'merchant_name': 'Uber',
  'name': 'Uber 063015 SF**POOL**',
  'payment_channel': 'online',
  'payment_meta': {'by_order_of': None,
                   'payee': None,
                   'payer': None,
                   'payment_method': None,
                   'payment_processor': None,
                   'ppd_id': None,
                   'reason': None,
                   'reference_number': None},
  'pending': False,
  'pending_transaction_id': None,
  'personal_finance_category': {'confidence_level': 'VERY_HIGH',
                                'detailed': 'TRANSPORTATION_TAXIS_AND_RIDE_SHARES',
                                'primary': 'TRANSPORTATION'},
  'personal_finance_category_icon_url': 'https://plaid-category-icons.plaid.com/PFC_TRANSPORTATION.png',
  'transaction_code': None,
  'transaction_id': 'ywNV9ZaEW8IjDaeZlrzgTKJB676VgKsKeZjmp',
  'transaction_type': 'special',
  'unofficial_currency_code': None,
  'website': 'uber.com'},
 {'account_id': '6pQgJ1wGb9I3RmEyN1ZGUeKjmpvnZkH8qGeJN',
  'account_owner': None,
  'amount': -4.22,
  'authorized_date': datetime.date(2023, 11, 21),
  'authorized_datetime': None,
  'category': ['Transfer', 'Payroll'],
  'category_id': '21009000',
  'check_number': None,
  'counterparties': [],
  'date': datetime.date(2023, 11, 21),
  'datetime': None,
  'iso_currency_code': 'USD',
  'location': {'address': None,
               'city': None,
               'country': None,
               'lat': None,
               'lon': None,
               'postal_code': None,
               'region': None,
               'store_number': None},
  'logo_url': None,
  'merchant_entity_id': None,
  'merchant_name': None,
  'name': 'INTRST PYMNT',
  'payment_channel': 'other',
  'payment_meta': {'by_order_of': None,
                   'payee': None,
                   'payer': None,
                   'payment_method': None,
                   'payment_processor': None,
                   'ppd_id': None,
                   'reason': None,
                   'reference_number': None},
  'pending': False,
  'pending_transaction_id': None,
  'personal_finance_category': {'confidence_level': 'LOW',
                                'detailed': 'INCOME_WAGES',
                                'primary': 'INCOME'},
  'personal_finance_category_icon_url': 'https://plaid-category-icons.plaid.com/PFC_INCOME.png',
  'transaction_code': None,
  'transaction_id': 'Rqd8J4epyxu5evjGgZPLH7P86R64e7hP3LDy6',
  'transaction_type': 'special',
  'unofficial_currency_code': None,
  'website': None},
 {'account_id': '6pQgJ1wGb9I3RmEyN1ZGUeKjmpvnZkH8qGeJN',
  'account_owner': None,
  'amount': 25.0,
  'authorized_date': datetime.date(2023, 10, 26),
  'authorized_datetime': None,
  'category': ['Payment', 'Credit Card'],
  'category_id': '16001000',
  'check_number': None,
  'counterparties': [],
  'date': datetime.date(2023, 10, 27),
  'datetime': None,
  'iso_currency_code': 'USD',
  'location': {'address': None,
               'city': None,
               'country': None,
               'lat': None,
               'lon': None,
               'postal_code': None,
               'region': None,
               'store_number': None},
  'logo_url': None,
  'merchant_entity_id': None,
  'merchant_name': None,
  'name': 'CREDIT CARD 3333 PAYMENT *//',
  'payment_channel': 'other',
  'payment_meta': {'by_order_of': None,
                   'payee': None,
                   'payer': None,
                   'payment_method': None,
                   'payment_processor': None,
                   'ppd_id': None,
                   'reason': None,
                   'reference_number': None},
  'pending': False,
  'pending_transaction_id': None,
  'personal_finance_category': {'confidence_level': 'LOW',
                                'detailed': 'LOAN_PAYMENTS_CREDIT_CARD_PAYMENT',
                                'primary': 'LOAN_PAYMENTS'},
  'personal_finance_category_icon_url': 'https://plaid-category-icons.plaid.com/PFC_LOAN_PAYMENTS.png',
  'transaction_code': None,
  'transaction_id': '6pQgJ1wGb9I3RmEyN1ZGUeKoBgBw9eT1LqNZV',
  'transaction_type': 'special',
  'unofficial_currency_code': None,
  'website': None},
 {'account_id': '6pQgJ1wGb9I3RmEyN1ZGUeKjmpvnZkH8qGeJN',
  'account_owner': None,
  'amount': -4.22,
  'authorized_date': datetime.date(2023, 10, 22),
  'authorized_datetime': None,
  'category': ['Transfer', 'Payroll'],
  'category_id': '21009000',
  'check_number': None,
  'counterparties': [],
  'date': datetime.date(2023, 10, 22),
  'datetime': None,
  'iso_currency_code': 'USD',
  'location': {'address': None,
               'city': None,
               'country': None,
               'lat': None,
               'lon': None,
               'postal_code': None,
               'region': None,
               'store_number': None},
  'logo_url': None,
  'merchant_entity_id': None,
  'merchant_name': None,
  'name': 'INTRST PYMNT',
  'payment_channel': 'other',
  'payment_meta': {'by_order_of': None,
                   'payee': None,
                   'payer': None,
                   'payment_method': None,
                   'payment_processor': None,
                   'ppd_id': None,
                   'reason': None,
                   'reference_number': None},
  'pending': False,
  'pending_transaction_id': None,
  'personal_finance_category': {'confidence_level': 'LOW',
                                'detailed': 'INCOME_WAGES',
                                'primary': 'INCOME'},
  'personal_finance_category_icon_url': 'https://plaid-category-icons.plaid.com/PFC_INCOME.png',
  'transaction_code': None,
  'transaction_id': 'Xx78pDNAVjIlPzDKy3EkFw1VxZxvGwI1qrVZo',
  'transaction_type': 'special',
  'unofficial_currency_code': None,
  'website': None},
 {'account_id': '6pQgJ1wGb9I3RmEyN1ZGUeKjmpvnZkH8qGeJN',
  'account_owner': None,
  'amount': 25.0,
  'authorized_date': datetime.date(2023, 9, 26),
  'authorized_datetime': None,
  'category': ['Payment', 'Credit Card'],
  'category_id': '16001000',
  'check_number': None,
  'counterparties': [],
  'date': datetime.date(2023, 9, 27),
  'datetime': None,
  'iso_currency_code': 'USD',
  'location': {'address': None,
               'city': None,
               'country': None,
               'lat': None,
               'lon': None,
               'postal_code': None,
               'region': None,
               'store_number': None},
  'logo_url': None,
  'merchant_entity_id': None,
  'merchant_name': None,
  'name': 'CREDIT CARD 3333 PAYMENT *//',
  'payment_channel': 'other',
  'payment_meta': {'by_order_of': None,
                   'payee': None,
                   'payer': None,
                   'payment_method': None,
                   'payment_processor': None,
                   'ppd_id': None,
                   'reason': None,
                   'reference_number': None},
  'pending': False,
  'pending_transaction_id': None,
  'personal_finance_category': {'confidence_level': 'LOW',
                                'detailed': 'LOAN_PAYMENTS_CREDIT_CARD_PAYMENT',
                                'primary': 'LOAN_PAYMENTS'},
  'personal_finance_category_icon_url': 'https://plaid-category-icons.plaid.com/PFC_LOAN_PAYMENTS.png',
  'transaction_code': None,
  'transaction_id': 'DJb8K9rkzdH579zayArnHloaZGZL5lt4xrVDy',
  'transaction_type': 'special',
  'unofficial_currency_code': None,
  'website': None},
 {'account_id': 'Xx78pDNAVjIlPzDKy3EkFw1d9nkQpLubryLgG',
  'account_owner': None,
  'amount': 1000.0,
  'authorized_date': None,
  'authorized_datetime': None,
  'category': ['Transfer', 'Deposit'],
  'category_id': '21007000',
  'check_number': None,
  'counterparties': [],
  'date': datetime.date(2023, 10, 26),
  'datetime': None,
  'iso_currency_code': 'USD',
  'location': {'address': None,
               'city': None,
               'country': None,
               'lat': None,
               'lon': None,
               'postal_code': None,
               'region': None,
               'store_number': None},
  'logo_url': None,
  'merchant_entity_id': None,
  'merchant_name': None,
  'name': 'CD DEPOSIT .INITIAL.',
  'payment_channel': 'other',
  'payment_meta': {'by_order_of': None,
                   'payee': None,
                   'payer': None,
                   'payment_method': None,
                   'payment_processor': None,
                   'ppd_id': None,
                   'reason': None,
                   'reference_number': None},
  'pending': False,
  'pending_transaction_id': None,
  'personal_finance_category': {'confidence_level': 'LOW',
                                'detailed': 'GENERAL_MERCHANDISE_OTHER_GENERAL_MERCHANDISE',
                                'primary': 'GENERAL_MERCHANDISE'},
  'personal_finance_category_icon_url': 'https://plaid-category-icons.plaid.com/PFC_GENERAL_MERCHANDISE.png',
  'transaction_code': None,
  'transaction_id': '5keoz1wAM9HEXzD1x9WQIBjPEGEA3BuGMERm9',
  'transaction_type': 'special',
  'unofficial_currency_code': None,
  'website': None},
 {'account_id': 'Xx78pDNAVjIlPzDKy3EkFw1d9nkQpLubryLgG',
  'account_owner': None,
  'amount': 1000.0,
  'authorized_date': None,
  'authorized_datetime': None,
  'category': ['Transfer', 'Deposit'],
  'category_id': '21007000',
  'check_number': None,
  'counterparties': [],
  'date': datetime.date(2023, 9, 26),
  'datetime': None,
  'iso_currency_code': 'USD',
  'location': {'address': None,
               'city': None,
               'country': None,
               'lat': None,
               'lon': None,
               'postal_code': None,
               'region': None,
               'store_number': None},
  'logo_url': None,
  'merchant_entity_id': None,
  'merchant_name': None,
  'name': 'CD DEPOSIT .INITIAL.',
  'payment_channel': 'other',
  'payment_meta': {'by_order_of': None,
                   'payee': None,
                   'payer': None,
                   'payment_method': None,
                   'payment_processor': None,
                   'ppd_id': None,
                   'reason': None,
                   'reference_number': None},
  'pending': False,
  'pending_transaction_id': None,
  'personal_finance_category': {'confidence_level': 'LOW',
                                'detailed': 'GENERAL_MERCHANDISE_OTHER_GENERAL_MERCHANDISE',
                                'primary': 'GENERAL_MERCHANDISE'},
  'personal_finance_category_icon_url': 'https://plaid-category-icons.plaid.com/PFC_GENERAL_MERCHANDISE.png',
  'transaction_code': None,
  'transaction_id': 'JJlEdKGjN7H51LKRXbgWH3Q7epe5v3FQqGaP9',
  'transaction_type': 'special',
  'unofficial_currency_code': None,
  'website': None},
 {'account_id': 'DJb8K9rkzdH579zayArnHlo39nQVKXc3rnJek',
  'account_owner': None,
  'amount': 78.5,
  'authorized_date': datetime.date(2023, 11, 23),
  'authorized_datetime': None,
  'category': ['Recreation', 'Gyms and Fitness Centers'],
  'category_id': '17018000',
  'check_number': None,
  'counterparties': [],
  'date': datetime.date(2023, 11, 24),
  'datetime': None,
  'iso_currency_code': 'USD',
  'location': {'address': None,
               'city': None,
               'country': None,
               'lat': None,
               'lon': None,
               'postal_code': None,
               'region': None,
               'store_number': None},
  'logo_url': None,
  'merchant_entity_id': None,
  'merchant_name': None,
  'name': 'Touchstone Climbing',
  'payment_channel': 'in store',
  'payment_meta': {'by_order_of': None,
                   'payee': None,
                   'payer': None,
                   'payment_method': None,
                   'payment_processor': None,
                   'ppd_id': None,
                   'reason': None,
                   'reference_number': None},
  'pending': False,
  'pending_transaction_id': None,
  'personal_finance_category': {'confidence_level': 'LOW',
                                'detailed': 'PERSONAL_CARE_GYMS_AND_FITNESS_CENTERS',
                                'primary': 'PERSONAL_CARE'},
  'personal_finance_category_icon_url': 'https://plaid-category-icons.plaid.com/PFC_PERSONAL_CARE.png',
  'transaction_code': None,
  'transaction_id': 'BJGRNgqBK3HE1onQ38rKIMg95E5bzMizn1dlv',
  'transaction_type': 'place',
  'unofficial_currency_code': None,
  'website': None},
 {'account_id': 'DJb8K9rkzdH579zayArnHlo39nQVKXc3rnJek',
  'account_owner': None,
  'amount': 500.0,
  'authorized_date': None,
  'authorized_datetime': None,
  'category': ['Travel', 'Airlines and Aviation Services'],
  'category_id': '22001000',
  'check_number': None,
  'counterparties': [{'confidence_level': 'VERY_HIGH',
                      'entity_id': 'NKDjqyAdQQzpyeD8qpLnX0D6yvLe2KYKYYzQ4',
                      'logo_url': 'https://plaid-merchant-logos.plaid.com/united_airlines_1065.png',
                      'name': 'United Airlines',
                      'phone_number': None,
                      'type': 'merchant',
                      'website': 'united.com'}],
  'date': datetime.date(2023, 11, 11),
  'datetime': None,
  'iso_currency_code': 'USD',
  'location': {'address': None,
               'city': None,
               'country': None,
               'lat': None,
               'lon': None,
               'postal_code': None,
               'region': None,
               'store_number': None},
  'logo_url': 'https://plaid-merchant-logos.plaid.com/united_airlines_1065.png',
  'merchant_entity_id': 'NKDjqyAdQQzpyeD8qpLnX0D6yvLe2KYKYYzQ4',
  'merchant_name': 'United Airlines',
  'name': 'United Airlines',
  'payment_channel': 'in store',
  'payment_meta': {'by_order_of': None,
                   'payee': None,
                   'payer': None,
                   'payment_method': None,
                   'payment_processor': None,
                   'ppd_id': None,
                   'reason': None,
                   'reference_number': None},
  'pending': False,
  'pending_transaction_id': None,
  'personal_finance_category': {'confidence_level': 'VERY_HIGH',
                                'detailed': 'TRAVEL_FLIGHTS',
                                'primary': 'TRAVEL'},
  'personal_finance_category_icon_url': 'https://plaid-category-icons.plaid.com/PFC_TRAVEL.png',
  'transaction_code': None,
  'transaction_id': '3MjKVDWEX9IRngAZvb6mSEk6pVpJWEsm3Lkxb',
  'transaction_type': 'special',
  'unofficial_currency_code': None,
  'website': 'united.com'},
 {'account_id': 'DJb8K9rkzdH579zayArnHlo39nQVKXc3rnJek',
  'account_owner': None,
  'amount': 500.0,
  'authorized_date': None,
  'authorized_datetime': None,
  'category': ['Food and Drink', 'Restaurants'],
  'category_id': '13005000',
  'check_number': None,
  'counterparties': [],
  'date': datetime.date(2023, 11, 6),
  'datetime': None,
  'iso_currency_code': 'USD',
  'location': {'address': None,
               'city': None,
               'country': None,
               'lat': None,
               'lon': None,
               'postal_code': None,
               'region': None,
               'store_number': None},
  'logo_url': None,
  'merchant_entity_id': None,
  'merchant_name': None,
  'name': 'Tectra Inc',
  'payment_channel': 'in store',
  'payment_meta': {'by_order_of': None,
                   'payee': None,
                   'payer': None,
                   'payment_method': None,
                   'payment_processor': None,
                   'ppd_id': None,
                   'reason': None,
                   'reference_number': None},
  'pending': False,
  'pending_transaction_id': None,
  'personal_finance_category': {'confidence_level': 'LOW',
                                'detailed': 'ENTERTAINMENT_SPORTING_EVENTS_AMUSEMENT_PARKS_AND_MUSEUMS',
                                'primary': 'ENTERTAINMENT'},
  'personal_finance_category_icon_url': 'https://plaid-category-icons.plaid.com/PFC_ENTERTAINMENT.png',
  'transaction_code': None,
  'transaction_id': 'xv4rLZd8WQHP5r8Q1WBjHDZyo6onlDCyvZxb4',
  'transaction_type': 'place',
  'unofficial_currency_code': None,
  'website': None},
 {'account_id': 'DJb8K9rkzdH579zayArnHlo39nQVKXc3rnJek',
  'account_owner': None,
  'amount': 500.0,
  'authorized_date': None,
  'authorized_datetime': None,
  'category': ['Shops', 'Sporting Goods'],
  'category_id': '19046000',
  'check_number': None,
  'counterparties': [],
  'date': datetime.date(2023, 11, 5),
  'datetime': None,
  'iso_currency_code': 'USD',
  'location': {'address': None,
               'city': None,
               'country': None,
               'lat': None,
               'lon': None,
               'postal_code': None,
               'region': None,
               'store_number': None},
  'logo_url': None,
  'merchant_entity_id': None,
  'merchant_name': None,
  'name': 'Madison Bicycle Shop',
  'payment_channel': 'in store',
  'payment_meta': {'by_order_of': None,
                   'payee': None,
                   'payer': None,
                   'payment_method': None,
                   'payment_processor': None,
                   'ppd_id': None,
                   'reason': None,
                   'reference_number': None},
  'pending': False,
  'pending_transaction_id': None,
  'personal_finance_category': {'confidence_level': 'LOW',
                                'detailed': 'GENERAL_MERCHANDISE_SPORTING_GOODS',
                                'primary': 'GENERAL_MERCHANDISE'},
  'personal_finance_category_icon_url': 'https://plaid-category-icons.plaid.com/PFC_GENERAL_MERCHANDISE.png',
  'transaction_code': None,
  'transaction_id': 'd1WweAlz3mtWbAZp3P78sPBqdodGKPtBeqvp1',
  'transaction_type': 'place',
  'unofficial_currency_code': None,
  'website': None},
 {'account_id': 'DJb8K9rkzdH579zayArnHlo39nQVKXc3rnJek',
  'account_owner': None,
  'amount': 500.0,
  'authorized_date': None,
  'authorized_datetime': None,
  'category': ['Food and Drink', 'Restaurants', 'Fast Food'],
  'category_id': '13005032',
  'check_number': None,
  'counterparties': [{'confidence_level': 'VERY_HIGH',
                      'entity_id': '3LmdknrdwVy9vm0dqj417rLKeJXW7veV7eb2e',
                      'logo_url': 'https://plaid-merchant-logos.plaid.com/kfc_546.png',
                      'name': 'KFC',
                      'phone_number': None,
                      'type': 'merchant',
                      'website': 'kfc.com'}],
  'date': datetime.date(2023, 11, 5),
  'datetime': None,
  'iso_currency_code': 'USD',
  'location': {'address': None,
               'city': None,
               'country': None,
               'lat': None,
               'lon': None,
               'postal_code': None,
               'region': None,
               'store_number': None},
  'logo_url': 'https://plaid-merchant-logos.plaid.com/kfc_546.png',
  'merchant_entity_id': '3LmdknrdwVy9vm0dqj417rLKeJXW7veV7eb2e',
  'merchant_name': 'KFC',
  'name': 'KFC',
  'payment_channel': 'in store',
  'payment_meta': {'by_order_of': None,
                   'payee': None,
                   'payer': None,
                   'payment_method': None,
                   'payment_processor': None,
                   'ppd_id': None,
                   'reason': None,
                   'reference_number': None},
  'pending': False,
  'pending_transaction_id': None,
  'personal_finance_category': {'confidence_level': 'VERY_HIGH',
                                'detailed': 'FOOD_AND_DRINK_FAST_FOOD',
                                'primary': 'FOOD_AND_DRINK'},
  'personal_finance_category_icon_url': 'https://plaid-category-icons.plaid.com/PFC_FOOD_AND_DRINK.png',
  'transaction_code': None,
  'transaction_id': 'aQgeJLEqrmCvoX6a9DReIWkPKDKdLWikLv8MB',
  'transaction_type': 'place',
  'unofficial_currency_code': None,
  'website': 'kfc.com'},
 {'account_id': 'DJb8K9rkzdH579zayArnHlo39nQVKXc3rnJek',
  'account_owner': None,
  'amount': 2078.5,
  'authorized_date': None,
  'authorized_datetime': None,
  'category': ['Payment'],
  'category_id': '16000000',
  'check_number': None,
  'counterparties': [],
  'date': datetime.date(2023, 11, 5),
  'datetime': None,
  'iso_currency_code': 'USD',
  'location': {'address': None,
               'city': None,
               'country': None,
               'lat': None,
               'lon': None,
               'postal_code': None,
               'region': None,
               'store_number': None},
  'logo_url': None,
  'merchant_entity_id': None,
  'merchant_name': None,
  'name': 'AUTOMATIC PAYMENT - THANK',
  'payment_channel': 'online',
  'payment_meta': {'by_order_of': None,
                   'payee': None,
                   'payer': None,
                   'payment_method': None,
                   'payment_processor': None,
                   'ppd_id': None,
                   'reason': None,
                   'reference_number': None},
  'pending': False,
  'pending_transaction_id': None,
  'personal_finance_category': {'confidence_level': 'LOW',
                                'detailed': 'GENERAL_MERCHANDISE_OTHER_GENERAL_MERCHANDISE',
                                'primary': 'GENERAL_MERCHANDISE'},
  'personal_finance_category_icon_url': 'https://plaid-category-icons.plaid.com/PFC_GENERAL_MERCHANDISE.png',
  'transaction_code': None,
  'transaction_id': '417rwg3WkJtE7VDJwAyxIzXKpvpEjzfl7KXPx',
  'transaction_type': 'special',
  'unofficial_currency_code': None,
  'website': None},
 {'account_id': 'DJb8K9rkzdH579zayArnHlo39nQVKXc3rnJek',
  'account_owner': None,
  'amount': 78.5,
  'authorized_date': datetime.date(2023, 10, 24),
  'authorized_datetime': None,
  'category': ['Recreation', 'Gyms and Fitness Centers'],
  'category_id': '17018000',
  'check_number': None,
  'counterparties': [],
  'date': datetime.date(2023, 10, 25),
  'datetime': None,
  'iso_currency_code': 'USD',
  'location': {'address': None,
               'city': None,
               'country': None,
               'lat': None,
               'lon': None,
               'postal_code': None,
               'region': None,
               'store_number': None},
  'logo_url': None,
  'merchant_entity_id': None,
  'merchant_name': None,
  'name': 'Touchstone Climbing',
  'payment_channel': 'in store',
  'payment_meta': {'by_order_of': None,
                   'payee': None,
                   'payer': None,
                   'payment_method': None,
                   'payment_processor': None,
                   'ppd_id': None,
                   'reason': None,
                   'reference_number': None},
  'pending': False,
  'pending_transaction_id': None,
  'personal_finance_category': {'confidence_level': 'LOW',
                                'detailed': 'PERSONAL_CARE_GYMS_AND_FITNESS_CENTERS',
                                'primary': 'PERSONAL_CARE'},
  'personal_finance_category_icon_url': 'https://plaid-category-icons.plaid.com/PFC_PERSONAL_CARE.png',
  'transaction_code': None,
  'transaction_id': 'NJzRV3eZjrH5VQygAR8KH4XnBpBkr4FXmzEwD',
  'transaction_type': 'place',
  'unofficial_currency_code': None,
  'website': None},
 {'account_id': 'DJb8K9rkzdH579zayArnHlo39nQVKXc3rnJek',
  'account_owner': None,
  'amount': 500.0,
  'authorized_date': None,
  'authorized_datetime': None,
  'category': ['Travel', 'Airlines and Aviation Services'],
  'category_id': '22001000',
  'check_number': None,
  'counterparties': [{'confidence_level': 'VERY_HIGH',
                      'entity_id': 'NKDjqyAdQQzpyeD8qpLnX0D6yvLe2KYKYYzQ4',
                      'logo_url': 'https://plaid-merchant-logos.plaid.com/united_airlines_1065.png',
                      'name': 'United Airlines',
                      'phone_number': None,
                      'type': 'merchant',
                      'website': 'united.com'}],
  'date': datetime.date(2023, 10, 12),
  'datetime': None,
  'iso_currency_code': 'USD',
  'location': {'address': None,
               'city': None,
               'country': None,
               'lat': None,
               'lon': None,
               'postal_code': None,
               'region': None,
               'store_number': None},
  'logo_url': 'https://plaid-merchant-logos.plaid.com/united_airlines_1065.png',
  'merchant_entity_id': 'NKDjqyAdQQzpyeD8qpLnX0D6yvLe2KYKYYzQ4',
  'merchant_name': 'United Airlines',
  'name': 'United Airlines',
  'payment_channel': 'in store',
  'payment_meta': {'by_order_of': None,
                   'payee': None,
                   'payer': None,
                   'payment_method': None,
                   'payment_processor': None,
                   'ppd_id': None,
                   'reason': None,
                   'reference_number': None},
  'pending': False,
  'pending_transaction_id': None,
  'personal_finance_category': {'confidence_level': 'VERY_HIGH',
                                'detailed': 'TRAVEL_FLIGHTS',
                                'primary': 'TRAVEL'},
  'personal_finance_category_icon_url': 'https://plaid-category-icons.plaid.com/PFC_TRAVEL.png',
  'transaction_code': None,
  'transaction_id': 'PJ3bRdy1ZBH5X4WrqQLJHPXK6p6vzPtXZnGRD',
  'transaction_type': 'special',
  'unofficial_currency_code': None,
  'website': 'united.com'},
 {'account_id': 'DJb8K9rkzdH579zayArnHlo39nQVKXc3rnJek',
  'account_owner': None,
  'amount': 500.0,
  'authorized_date': None,
  'authorized_datetime': None,
  'category': ['Food and Drink', 'Restaurants'],
  'category_id': '13005000',
  'check_number': None,
  'counterparties': [],
  'date': datetime.date(2023, 10, 7),
  'datetime': None,
  'iso_currency_code': 'USD',
  'location': {'address': None,
               'city': None,
               'country': None,
               'lat': None,
               'lon': None,
               'postal_code': None,
               'region': None,
               'store_number': None},
  'logo_url': None,
  'merchant_entity_id': None,
  'merchant_name': None,
  'name': 'Tectra Inc',
  'payment_channel': 'in store',
  'payment_meta': {'by_order_of': None,
                   'payee': None,
                   'payer': None,
                   'payment_method': None,
                   'payment_processor': None,
                   'ppd_id': None,
                   'reason': None,
                   'reference_number': None},
  'pending': False,
  'pending_transaction_id': None,
  'personal_finance_category': {'confidence_level': 'LOW',
                                'detailed': 'ENTERTAINMENT_SPORTING_EVENTS_AMUSEMENT_PARKS_AND_MUSEUMS',
                                'primary': 'ENTERTAINMENT'},
  'personal_finance_category_icon_url': 'https://plaid-category-icons.plaid.com/PFC_ENTERTAINMENT.png',
  'transaction_code': None,
  'transaction_id': 'jvyb3Ke4m8HANEw3KoR5IWjNaAaGdWivqjPeE',
  'transaction_type': 'place',
  'unofficial_currency_code': None,
  'website': None},
 {'account_id': 'DJb8K9rkzdH579zayArnHlo39nQVKXc3rnJek',
  'account_owner': None,
  'amount': 500.0,
  'authorized_date': None,
  'authorized_datetime': None,
  'category': ['Shops', 'Sporting Goods'],
  'category_id': '19046000',
  'check_number': None,
  'counterparties': [],
  'date': datetime.date(2023, 10, 6),
  'datetime': None,
  'iso_currency_code': 'USD',
  'location': {'address': None,
               'city': None,
               'country': None,
               'lat': None,
               'lon': None,
               'postal_code': None,
               'region': None,
               'store_number': None},
  'logo_url': None,
  'merchant_entity_id': None,
  'merchant_name': None,
  'name': 'Madison Bicycle Shop',
  'payment_channel': 'in store',
  'payment_meta': {'by_order_of': None,
                   'payee': None,
                   'payer': None,
                   'payment_method': None,
                   'payment_processor': None,
                   'ppd_id': None,
                   'reason': None,
                   'reference_number': None},
  'pending': False,
  'pending_transaction_id': None,
  'personal_finance_category': {'confidence_level': 'LOW',
                                'detailed': 'GENERAL_MERCHANDISE_SPORTING_GOODS',
                                'primary': 'GENERAL_MERCHANDISE'},
  'personal_finance_category_icon_url': 'https://plaid-category-icons.plaid.com/PFC_GENERAL_MERCHANDISE.png',
  'transaction_code': None,
  'transaction_id': '7oZpvWJn59tER3DNpy6ZIxX4qBqaVxc8LaRq5',
  'transaction_type': 'place',
  'unofficial_currency_code': None,
  'website': None},
 {'account_id': 'DJb8K9rkzdH579zayArnHlo39nQVKXc3rnJek',
  'account_owner': None,
  'amount': 500.0,
  'authorized_date': None,
  'authorized_datetime': None,
  'category': ['Food and Drink', 'Restaurants', 'Fast Food'],
  'category_id': '13005032',
  'check_number': None,
  'counterparties': [{'confidence_level': 'VERY_HIGH',
                      'entity_id': '3LmdknrdwVy9vm0dqj417rLKeJXW7veV7eb2e',
                      'logo_url': 'https://plaid-merchant-logos.plaid.com/kfc_546.png',
                      'name': 'KFC',
                      'phone_number': None,
                      'type': 'merchant',
                      'website': 'kfc.com'}],
  'date': datetime.date(2023, 10, 6),
  'datetime': None,
  'iso_currency_code': 'USD',
  'location': {'address': None,
               'city': None,
               'country': None,
               'lat': None,
               'lon': None,
               'postal_code': None,
               'region': None,
               'store_number': None},
  'logo_url': 'https://plaid-merchant-logos.plaid.com/kfc_546.png',
  'merchant_entity_id': '3LmdknrdwVy9vm0dqj417rLKeJXW7veV7eb2e',
  'merchant_name': 'KFC',
  'name': 'KFC',
  'payment_channel': 'in store',
  'payment_meta': {'by_order_of': None,
                   'payee': None,
                   'payer': None,
                   'payment_method': None,
                   'payment_processor': None,
                   'ppd_id': None,
                   'reason': None,
                   'reference_number': None},
  'pending': False,
  'pending_transaction_id': None,
  'personal_finance_category': {'confidence_level': 'VERY_HIGH',
                                'detailed': 'FOOD_AND_DRINK_FAST_FOOD',
                                'primary': 'FOOD_AND_DRINK'},
  'personal_finance_category_icon_url': 'https://plaid-category-icons.plaid.com/PFC_FOOD_AND_DRINK.png',
  'transaction_code': None,
  'transaction_id': 'eLAv48qBxmUjAeZbwp7yTXlkJ5JrQXta1X8Gd',
  'transaction_type': 'place',
  'unofficial_currency_code': None,
  'website': 'kfc.com'},
 {'account_id': 'DJb8K9rkzdH579zayArnHlo39nQVKXc3rnJek',
  'account_owner': None,
  'amount': 2078.5,
  'authorized_date': None,
  'authorized_datetime': None,
  'category': ['Payment'],
  'category_id': '16000000',
  'check_number': None,
  'counterparties': [],
  'date': datetime.date(2023, 10, 6),
  'datetime': None,
  'iso_currency_code': 'USD',
  'location': {'address': None,
               'city': None,
               'country': None,
               'lat': None,
               'lon': None,
               'postal_code': None,
               'region': None,
               'store_number': None},
  'logo_url': None,
  'merchant_entity_id': None,
  'merchant_name': None,
  'name': 'AUTOMATIC PAYMENT - THANK',
  'payment_channel': 'online',
  'payment_meta': {'by_order_of': None,
                   'payee': None,
                   'payer': None,
                   'payment_method': None,
                   'payment_processor': None,
                   'ppd_id': None,
                   'reason': None,
                   'reference_number': None},
  'pending': False,
  'pending_transaction_id': None,
  'personal_finance_category': {'confidence_level': 'LOW',
                                'detailed': 'GENERAL_MERCHANDISE_OTHER_GENERAL_MERCHANDISE',
                                'primary': 'GENERAL_MERCHANDISE'},
  'personal_finance_category_icon_url': 'https://plaid-category-icons.plaid.com/PFC_GENERAL_MERCHANDISE.png',
  'transaction_code': None,
  'transaction_id': 'QlxJQaeLG3I5JKRGwmPdHjNrgxg3RjFGEn9Vo',
  'transaction_type': 'special',
  'unofficial_currency_code': None,
  'website': None},
 {'account_id': 'VBPWo7XEyNH561VNEZovHMq3gxjL7Wi9vREkX',
  'account_owner': None,
  'amount': 5850.0,
  'authorized_date': None,
  'authorized_datetime': None,
  'category': ['Transfer', 'Debit'],
  'category_id': '21006000',
  'check_number': None,
  'counterparties': [],
  'date': datetime.date(2023, 10, 26),
  'datetime': None,
  'iso_currency_code': 'USD',
  'location': {'address': None,
               'city': None,
               'country': None,
               'lat': None,
               'lon': None,
               'postal_code': None,
               'region': None,
               'store_number': None},
  'logo_url': None,
  'merchant_entity_id': None,
  'merchant_name': None,
  'name': 'ACH Electronic CreditGUSTO PAY 123456',
  'payment_channel': 'online',
  'payment_meta': {'by_order_of': None,
                   'payee': None,
                   'payer': None,
                   'payment_method': 'ACH',
                   'payment_processor': None,
                   'ppd_id': None,
                   'reason': None,
                   'reference_number': None},
  'pending': False,
  'pending_transaction_id': None,
  'personal_finance_category': {'confidence_level': 'LOW',
                                'detailed': 'GENERAL_SERVICES_ACCOUNTING_AND_FINANCIAL_PLANNING',
                                'primary': 'GENERAL_SERVICES'},
  'personal_finance_category_icon_url': 'https://plaid-category-icons.plaid.com/PFC_GENERAL_SERVICES.png',
  'transaction_code': None,
  'transaction_id': '1QNlrDegM9CqvGEPbWjdIr6vNWNAKrtqla41a',
  'transaction_type': 'special',
  'unofficial_currency_code': None,
  'website': None},
 {'account_id': 'VBPWo7XEyNH561VNEZovHMq3gxjL7Wi9vREkX',
  'account_owner': None,
  'amount': 5850.0,
  'authorized_date': None,
  'authorized_datetime': None,
  'category': ['Transfer', 'Debit'],
  'category_id': '21006000',
  'check_number': None,
  'counterparties': [],
  'date': datetime.date(2023, 9, 26),
  'datetime': None,
  'iso_currency_code': 'USD',
  'location': {'address': None,
               'city': None,
               'country': None,
               'lat': None,
               'lon': None,
               'postal_code': None,
               'region': None,
               'store_number': None},
  'logo_url': None,
  'merchant_entity_id': None,
  'merchant_name': None,
  'name': 'ACH Electronic CreditGUSTO PAY 123456',
  'payment_channel': 'online',
  'payment_meta': {'by_order_of': None,
                   'payee': None,
                   'payer': None,
                   'payment_method': 'ACH',
                   'payment_processor': None,
                   'ppd_id': None,
                   'reason': None,
                   'reference_number': None},
  'pending': False,
  'pending_transaction_id': None,
  'personal_finance_category': {'confidence_level': 'LOW',
                                'detailed': 'GENERAL_SERVICES_ACCOUNTING_AND_FINANCIAL_PLANNING',
                                'primary': 'GENERAL_SERVICES'},
  'personal_finance_category_icon_url': 'https://plaid-category-icons.plaid.com/PFC_GENERAL_SERVICES.png',
  'transaction_code': None,
  'transaction_id': 'LJKVGzReNqH5wJzRrjpDHdeZLKLavdueGm154',
  'transaction_type': 'special',
  'unofficial_currency_code': None,
  'website': None}]


